server:
  port: 8072

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/
  management:
    endpoints:
      web:
        exposure:
          include: "*"

spring:
  cloud:
    gateway:
      discovery.locator:
        enabled: true
        lowerCaseServiceId: true

#spring:
#cloud:
#gateway:
#routes:
#  - id: fractures
#    uri: lb://fractures
#    predicates:
#      - Path=/register/**
#    filters:
#      - RewritePath=/register/(?<path>.*), /$\{path}

